apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flow-nifi-0
  namespace: teamb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: flow-teamb-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flow-nifi-1
  namespace: teamb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: flow-teamb-1
