apiVersion: v1
kind: PersistentVolume
metadata:
  name: content-teamb-0
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/  /repo/content/teamB"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gke-cluster-1-default-pool-e82b3219-n1d2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: content-teamb-1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/stateful_partition/repo/content/teamB"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gke-cluster-1-default-pool-e82b3219-q2p6
