apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
  creationTimestamp: "2022-09-13T10:33:03Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: nifi
    release: myrel
  name: auth-conf-myrel-nifi-0
  namespace: default
  resourceVersion: "23292"
  uid: 545890ec-be22-490a-bfec-3016d34b1b8a
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-545890ec-be22-490a-bfec-3016d34b1b8a
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
